[book]
authors = ["Vilagcraft"]
language = "ru"
multilingual = false
src = "src"
title = "Системная инженерия. RocketSpot"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
# Используем кастомную тему
theme = "theme"
# Включаем Mermaid
additional-css = ["src/_assets/custom.css"]
additional-js = []

[output.html.print]
enable = true
